### ISSUE TITLE
Support for V14

### ISSUE THREAD

**Issue by blewsky** [alyf-de/pdf_on_submit#23]
Please publish the app on Frappe Cloud market place for Version 14. Currently, only V13 and V12 are supported.
Version 14 has been out since several weeks and we would like to migrate to V14 as soon as our installed apps are supported on V14.
Do you have a rough time plan until when this could be achieved? In case this is not planned right now, we might prefer to drop the integration and migrate to V14 without it if it takes a bit longer.
Thank you.

**Comment by barredterra** [comment]
@blewsky we now have a `version-14` branch. Thanks for your patience!

**Comment by blewsky** [comment]
Awesome, thanks @barredterra! Will this be uploaded to https://frappecloud.com/marketplace/apps/pdf-on-submit soon as well? Thanks

**Comment by barredterra** [comment]
@blewsky yes, I already requested a release on Frappe Cloud.
