### ISSUE TITLE
FR28 causes v13 to fail submits on any doctypes because of missing weasyprint

### ISSUE THREAD

**Issue by pgruener** [alyf-de/pdf_on_submit#30]
Caused by https://github.com/alyf-de/erpnext_pdf-on-submit/pull/28

After we updated the app, we cannot submit any documents anymore.

I think I ready weasyprint is for v14, but hope that's not misleading here.

I attached the error backtrace here:
![image](https://user-images.githubusercontent.com/110686/205004385-07a68d7b-c965-4bfe-b61b-a0515f6d182c.png)

Perhaps weasyprint can be added to the requirements if I am wrong with my information to be related to v14?

But for now we needed to deinstall the app quickly; would be great if the dependencies could be checked or made somehow other (backwards) compatible

Let me know if you need more details.

**Comment by barredterra** [comment]
Hi @pgruener, I checked the latest frappe v14 release: it definitely has a module `frappe.utils.weasyprint`.

Do you maybe use the `version-14` or `develop` branch of pdf_on_submit in combination with frappe `version-13`? The installed branch of pdf_on_submit should always match the installed branch of frappe.

Try to reinstall the correct branch:

```bash

bench --site $MY_SITE uninstall-app pdf_on_submit  # repeat for all sites
bench remove-app pdf_on_submit
bench get-app --branch version-13 https://github.com/alyf-de/erpnext_pdf-on-submit.git
bench --site $MY_SITE install-app pdf_on_submit  # repeat for all sites
```

**Comment by pgruener** [comment]
Hi @barredterra that might be the reason. When you choose your app in the frappe cloud you only can choose the "master" branch; so I was using that with erpnext-v13. And until the mentioned commit it worked well.

No idea, why it is called "master", even if there is no master branch. Who is responsible for the mapping there?

![image](https://user-images.githubusercontent.com/110686/211524558-328c850c-03b6-4d46-b906-0f57b0556e0f.png)

**Comment by barredterra** [comment]
@pgruener, I'm in touch with the Frappe Cloud team to get the recent releases approved.
