### ISSUE TITLE
PrintFormatBeta, enabled_doctype

### ISSUE THREAD

**Issue by knudeh** [alyf-de/pdf_on_submit#31]
Many thanks for adapting pdf_on_submit for PrintFormatBeat.

I think there is an erorr in attach_pdf.py

28 def attach_pdf(doc, event=None):
29    settings = frappe.get_single("PDF on Submit Settings")
30
31     if enabled_doctypes := settings.get("enabled_for", {"document_type": doc.doctype}):
32         enabled_doctype = enabled_doctypes[0]
33     else:
34         return

The enabled doctypes are stored in its own tabEnabled Doctype an not in tabSingles. So enabled_doctypes[] is empty. 
On line 90 will always False and doctypes with PrintFormatBeta wont get printed. 
If I set line 90 to if (True): and i have doctypes with PrintFormatBeta they will print fine.

**Comment by barredterra** [comment]
Hi @knudeh , did you test this? Seems to work just fine:

```
> bench console
Apps in this namespace:
frappe, pdf_on_submit

In: settings = frappe.get_single("PDF on Submit Settings")

In: [row.document_type for row in settings.enabled_for]
Out: ['Test Submittable DocType']

In: settings.get("enabled_for", {"document_type": "Test Submittable DocType"})
Out: [<EnabledDocType: 41c0835496 parent=PDF on Submit Settings>]

In: enabled_doctypes = settings.get("enabled_for", {"document_type": "Test Submittable DocType"})
In: enabled_doctypes[0]
Out: <EnabledDocType: 41c0835496 parent=PDF on Submit Settings>
```
