### ISSUE TITLE
Error when creating Stock Entry

### ISSUE THREAD

**Issue by wojosc** [alyf-de/pdf_on_submit#33]
Hi,

since a recent update I get an error when trying to create a Stock Entry:

> ### App Versions
> ```
> {
> 	"erpnext": "13.42.5",
> 	"fieldtime_tracker": "0.0.1",
> 	"frappe": "13.46.1",
> 	"pdf_on_submit": "13.2",
> 	"stock_addon": "0.0.1"
> }
> ```
> ### Route
> ```
> Form/Stock Entry/MAT-STE-2022-00145
> ```
> ### Trackeback
> ```
> Traceback (most recent call last):
>   File "apps/frappe/frappe/app.py", line 69, in application
>     response = frappe.api.handle()
>   File "apps/frappe/frappe/api.py", line 55, in handle
>     return frappe.handler.handle()
>   File "apps/frappe/frappe/handler.py", line 38, in handle
>     data = execute_cmd(cmd)
>   File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "apps/frappe/frappe/__init__.py", line 1457, in call
>     return fn(*args, **newargs)
>   File "apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.submit()
>   File "apps/frappe/frappe/model/document.py", line 1019, in submit
>     return self._submit()
>   File "apps/frappe/frappe/model/document.py", line 1008, in _submit
>     return self.save()
>   File "apps/frappe/frappe/model/document.py", line 311, in save
>     return self._save(*args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 365, in _save
>     self.run_post_save_methods()
>   File "apps/frappe/frappe/model/document.py", line 1089, in run_post_save_methods
>     self.run_method("on_submit")
>   File "apps/frappe/frappe/model/document.py", line 942, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 1262, in composer
>     hooks.append(frappe.get_attr(handler))
>   File "apps/frappe/frappe/__init__.py", line 1447, in get_attr
>     return getattr(get_module(modulename), methodname)
>   File "apps/frappe/frappe/__init__.py", line 1200, in get_module
>     return importlib.import_module(modulename)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 860, in get_code
>   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "apps/pdf_on_submit/pdf_on_submit/attach_pdf.py", line 31
>     if enabled_doctypes := settings.get("enabled_for", {"document_type": doc.doctype}):
>                          ^
> SyntaxError: invalid syntax
> 
> ```
> ### Request Data
> ```
> {
> 	"type": "POST",
> 	"args": {
> 		"doc": "{\"name\":\"MAT-STE-2022-00145\",\"owner\":\"Administrator\",\"creation\":\"2022-12-20 14:24:31.437776\",\"modified\":\"2022-12-20 17:42:14.923304\",\"modified_by\":\"Administrator\",\"idx\":0,\"docstatus\":0,\"naming_series\":\"MAT-STE-.YYYY.-\",\"stock_entry_type\":\"Annahme\",\"purpose\":\"Material Receipt\",\"add_to_transit\":0,\"company\":\"Company GmbH\",\"posting_date\":\"2022-12-20\",\"posting_time\":\"17:42:14.95409\",\"set_posting_time\":0,\"inspection_required\":0,\"from_bom\":0,\"apply_putaway_rule\":0,\"fg_completed_qty\":0,\"use_multi_level_bom\":1,\"total_outgoing_value\":0,\"total_incoming_value\":0,\"value_difference\":0,\"total_additional_costs\":0,\"project\":\"\",\"zustand\":\"Neu\",\"letter_head\":\"Default Letter Head\",\"is_opening\":\"No\",\"per_transferred\":0,\"total_amount\":0,\"is_return\":0,\"doctype\":\"Stock Entry\",\"items\":[{\"name\":\"a85dd0c5c6\",\"owner\":\"Administrator\",\"creation\":\"2022-12-20 14:24:31.437776\",\"modified\":\"2022-12-20 17:42:14.923304\",\"modified_by\":\"Administrator\",\"parent\":\"MAT-STE-2022-00145\",\"parentfield\":\"items\",\"parenttype\":\"Stock Entry\",\"idx\":1,\"docstatus\":0,\"t_warehouse\":\"B5O_18 - SC\",\"item_code\":\"RESU 10M\",\"item_name\":\"LG Chem RESU 10M\",\"is_finished_item\":0,\"is_scrap_item\":0,\"is_process_loss\":0,\"description\":\"LG Chem *RESU 10M\",\"item_group\":\"Batterie\",\"image\":\"/files/RESU10M_24dVfWYDVmnpkP.jpg\",\"qty\":1,\"transfer_qty\":1,\"retain_sample\":0,\"uom\":\"Stk\",\"stock_uom\":\"Stk\",\"conversion_factor\":1,\"sample_quantity\":0,\"basic_rate\":0,\"additional_cost\":0,\"valuation_rate\":0,\"allow_zero_valuation_rate\":1,\"set_basic_rate_manually\":0,\"basic_amount\":0,\"amount\":0,\"serial_no\":\"R5555555\",\"expense_account\":\"8977 - Bestandsveränderung Aufträge in Arbeit - SC\",\"cost_center\":\"0 - Haupt - SC\",\"project\":\"PS221967\",\"zustand\":\"Neu\",\"actual_qty\":0,\"transferred_qty\":0,\"allow_alternative_item\":0,\"doctype\":\"Stock Entry Detail\"}],\"additional_costs\":[],\"__last_sync_on\":\"2022-12-21T09:48:08.685Z\",\"address_display\":null,\"purchase_receipt_no\":null,\"supplier_address\":null,\"supplier_name\":null,\"supplier\":null,\"sales_invoice_no\":null,\"delivery_note_no\":null,\"customer_address\":null,\"customer_name\":null,\"customer\":null}",
> 		"action": "Submit"
> 	},
> 	"btn": {
> 		"jQuery224038353808349558341": {
> 			"events": {
> 				"click": [
> 					{
> 						"type": "click",
> 						"origType": "click",
> 						"guid": 566,
> 						"namespace": ""
> 					}
> 				]
> 			}
> 		}
> 	},
> 	"freeze": true,
> 	"headers": {},
> 	"error_handlers": {},
> 	"url": "/api/method/frappe.desk.form.save.savedocs"
> }
> ```
> ### Response Data
> ```
> {
> 	"exception": "SyntaxError: invalid syntax"
> }
> ```

I have not set the option, that a PDF is created on Stock Entry or any other DocType directly connected to this. My settings are:
![image](https://user-images.githubusercontent.com/22279621/208875820-6e9303a8-0d72-4ef7-8f51-dd99185d8e2a.png)

Any ideas? Thank you!

**Comment by barredterra** [comment]
Hi @wojosc, thanks for reporting. The latest `version-13` release, as of now, is `v13.4.1`. This error is already fixed there.
