### ISSUE TITLE
How have you hooked into the On-Submit?

### ISSUE THREAD

**Issue by oguruma1218** [alyf-de/pdf_on_submit#40]
I'm interested in extending this software to automatically send each submitted document/PDF to Amazon S3 (possible FTP and other transfer methods/protocols as well). 

I have a client that needs offsite backups of certain Documents created automatically. So, once the Document is submitted, the PDF would be sent to Amazon S3/FTP. 

Using your plugin, is there a way I can hook into the PDF creation and execute some code to send the PDF to where it needs to go?

**Comment by barredterra** [comment]
This app creates a new **File** and saves it. So you could hook into the `after_insert` event of the **File** doctype. Then, maybe check if it's a PDF file, or if it's attached to one of the DocTypes you're interested in.
