### ISSUE TITLE
PDF is not created in the customers language

### ISSUE THREAD

**Issue by markusrock** [alyf-de/pdf_on_submit#42]
The document created is always saved in the default language. If the customer's default language is different (e.g. English instead of German), this is not taken into account.

Installed Apps

ERPNext: v14.66.3 (HEAD)
ERPNext DATEV Integration: v14.1.3 (HEAD)
ERPNext Germany: v14.6.1 (HEAD)
ERPNext Shipping: v14.3.4 (HEAD)
Frappe Framework: v14.70.0 (HEAD)
Helpdesk: v0.10.0 (HEAD)
Frappe HR: v14.24.2 (HEAD)
PDF on Submit: v14.0.5 (HEAD)

**Comment by barredterra** [comment]
I cannot confirm this, we use multi-language prints all the time. Please ensure that 

1. the _Print Language_ of your submitted document is set correctly
2. your **Print Format** supports translation
3. there are translations for your translatable strings
